coverage:
  precision: 4
  round: down # how to round precision
  range: "80...100"

  status:
    # overall coverage
    project:
      default:
        enabled: yes
        target: auto # must increase from parent commit or pull request base
        if_no_uploads: error

    # coverage of the PR diff
    patch:
      default:
        enabled: yes
        if_no_uploads: error

    changes: true

comment:
  layout: "header, diff, changes, tree, uncovered"
  behavior: default # posts once then updates the comment, posts new if deleted
