coverage:
  precision: 4       # how many decimal places to display in the UI: 0 <= value <= 4
  round: down        # how coverage is rounded: down/up/nearest
  range: "85...100"  # custom range of coverage colors from red -> yellow -> green

  status:
    project:
      default:
        enabled: yes
        target: auto # must increase from parent commit or pull request base
        if_no_uploads: error

    patch:
      default:
        enabled: yes
        if_no_uploads: error

    changes: true


comment:
  layout: "header, diff, changes, tree, uncovered, suggestions"
  behavior: default # posts once then update, posts new if deleted
