coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: auto # must increase from parent commit or pull request base
        if_no_uploads: error

    patch:
      default:
        enabled: yes
        if_no_uploads: error

    changes: true


comment:
  layout: "header, diff, changes, tree, uncovered"
  behavior: default # posts once then update, posts new if deleted
